### ISSUE TITLE
Country, State and Location are mandatory

### ISSUE THREAD

**Issue by jsampedro77** [kekru/linux-utils#1]
https://github.com/kekru/linux-utils/blob/8e102c740948a0a160de9cad2f74b61edce89b17/cert-generate/create-certs.sh#L5

If left empty I get a "asn1 encoding routines:ASN1_mbstring_ncopy:string too short:crypto/asn1/a_mbstr.c:102:minsize=1" error.

Just setting som info makes the command happy.

Thanks for the script!

**Comment by kekru** [comment]
Hi Javier,
thanks for your message. I did not see that behaviour yet. Could you tell your version of openssl ?
Maybe this only occurs in special versions of openssl

**Comment by jsampedro77** [comment]
Hi Kevin, 
I am using  OpenSSL 1.1.0h-fips  27 Mar 2018

**Comment by kekru** [comment]
I tested it on my Ubuntu 18.04 and "OpenSSL 1.1.0g  2 Nov 2017" and got the same behavior.  
I added a few example values into the default string. See #2 :)
